#! /bin/sh
echo "+----------------------------+"
echo "| load project specific data |"
echo "+----------------------------+"
read -n 1 -p "for environment [d(evelopment)|p(roduction)] " e4r
echo 
case "$e4r" in
  d ) e4r="development";;
  p ) e4r="production";;
esac
if [ ${#e4r} -eq 1 ]; then
  echo "Bad input found: '$e4r' - aborting request."
  exit 1
fi
export RAILS_ENV="$e4r"
bundle exec rake import['db/projects/dmr/a1_codes.csv','A1Code']
bundle exec rake import['db/projects/dmr/a2_codes.csv','A2Code']
bundle exec rake import['db/projects/dmr/a3_codes.csv','A3Code']
bundle exec rake import['db/projects/dmr/a4_codes.csv','A4Code']
bundle exec rake import['db/projects/dmr/a5_codes.csv','A5Code']
bundle exec rake import['db/projects/dmr/a6_codes.csv','A6Code']
bundle exec rake import['db/projects/dmr/a7_codes.csv','A7Code']
bundle exec rake import['db/projects/dmr/a8_codes.csv','A8Code']
#
bundle exec rake import['db/projects/dmr/location_codes.csv','LocationCode']
bundle exec rake import['db/projects/dmr/network_lines.csv','NetworkLine']
bundle exec rake import['db/projects/dmr/network_stations.csv','NetworkStation']
bundle exec rake db:seed:network_stops
#
# the following file determines which is the project-specific document log 
# SiemensDocumentLog or ADocumentLog
#
cp -p db/projects/dmr/project_doc_log.rb app/models/
#
if [[ "$e4r" == p* ]]; then
 	cp -p db/projects/dmr/zzz.en.yml config/locales
 	echo -e "\n>>> Project-specific I18 file copied\n"
fi